spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ec
    username: root
    password: trieu
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
#        use_sql_comments: true
    hibernate:
      ddl-auto: update

jwt:
  secret: "Hs1rno/+4+mIyo4gkk49ymga6UOGG4FTYpo13KSxH20="
  expiration:
    access: 900000        
    refresh: 604800000
logging:
  level:
    org.springframework.security: DEBUG
