spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ec
    username: yourusername
    password: yourpassword
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
#        use_sql_comments: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
         google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
          scope: email,profile
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
jwt:
  secret: "${JWT_SECRET:your-jwt-secret-here}" 
  expiration:
    access: 20000
    refresh: 604800000
logging:
  level:
    org.springframework.security: DEBUG
