spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ec
    username: root
    password: Hoanghoahong789
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
#        use_sql_comments: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
         google:
          client-id: 480765217721-bs1l6q4tiab92gvk044uhc7qv1nh0v1d.apps.googleusercontent.com
          client-secret: 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
          scope: email,profile
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoanghuy140204@gmail.com
    password: bwjs hyjk cirz ohhs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: "Hs1rno/+4+mIyo4gkk49ymga6UOGG4FTYpo13KSxH20="
  expiration:
    access: 20000
    refresh: 604800000
logging:
  level:
    org.springframework.security: DEBUG
app:
  frontend-url: http://localhost:3000