spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ec
    username: root
    password: trieu123
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
#        use_sql_comments: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
         google:

          scope: email,profile
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
jwt:
  secret: "Hs1rno/+4+mIyo4gkk49ymga6UOGG4FTYpo13KSxH20="
  expiration:
    access: 20000
    refresh: 604800000
logging:
  level:
    org.springframework.security: DEBUG
